### ISSUE TITLE
Can't upgrade caddy with this module installed

### ISSUE THREAD

**Issue by musklor** [caddy-dns/ovh#1]
upgrade: download failed: download failed: HTTP 400: github.com/cad
dy-dns/ovh is not a registered Caddy module package path (id=317cd3
b2-08b3-43e2-91f0-1d0efac53184)

**Comment by mholt** [comment]
(This plugin just needs to be registered/claimed by the author on our website: https://caddyserver.com/account)

**Comment by b-bremer** [comment]
@gjung56 The plugin works flawlessly (when using xcaddy). It would be awesome if you could add the plugin to caddyserver.com

**Comment by musklor** [comment]
For the moment, I use xcaddy in order to build a new binary with plugins.

**Comment by gjung56** [comment]
https://caddyserver.com/docs/modules/dns.providers.ovh
