### ISSUE TITLE
Configuration examples

### ISSUE THREAD

**Issue by wsw70** [caddy-dns/ovh#3]
Would it be possible to provide more details about the various configuration items:

```
$OVH_ENDPOINT
$OVH_APPLICATION_KEY
$OVH_APPLICATION_SECRET
$OVH_CONSUMER_KEY
```

Where can I retrieve them in my OVH account?

**Comment by wsw70** [comment]
Everything is at https://github.com/libdns/ovh#authenticating - per the docs 🫥

**Comment by KaKi87** [comment]
Hi,

Coming from [`acme.sh`](https://github.com/acmesh-official/acme.sh), this looks way more complicated, with coding involved and all.

Is here any simplified setup available ?

Thanks
